const constants= {
    FETCH_PRODUCTS_BEGIN:"FETCH_PRODUCTS_BEGIN",
    FETCH_PRODUCTS_SUCCESS:"FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE:"FETCH_PRODUCTS_FAILURE",
    ADD_PRODUCT:"ADD_PRODUCT",
    SEARCH_PRODUCT:"SEARCH_PRODUCT",
    INCREMENT_VIEWED_PRODUCT_COUNT:"INCREMENT_VIEWED_PRODUCT_COUNT",
    DELETE_PRODUCT:"DELETE_PRODUCT",
    EDIT_PRODUCT:"EDIT_PRODUCT",
    SET_CURRENT_USER:"SET_CURRENT_USER",
    LOGOUT_USER:"LOGOUT_USER",

    SELECT_PRODUCT:"SELECT_PRODUCT",
    SELECTED_PRODUCT_DELETE:"SELECTED_PRODUCT_DELETE",
    TOGGLE_CART:"TOGGLE_CART",
    ADD_ITEM:"ADD_ITEM",
    CLEAR_ITEM_FROM_CART:"CLEAR_ITEM_FROM_CART",
    REMOVE_ITEM:"REMOVE_ITEM",

}

export default constants;