const constants= {
    FETCH_PRODUCTS_BEGIN:"FETCH_PRODUCTS_BEGIN",
    FETCH_PRODUCTS_SUCCESS:"FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE:"FETCH_PRODUCTS_FAILURE",
    ADD_PRODUCT:"ADD_PRODUCT",
    SEARCH_PRODUCT:"SEARCH_PRODUCT"
}

export default constants;